"""empty message

Revision ID: 9b403361c66d
Revises: 
Create Date: 2021-03-16 17:05:13.599581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b403361c66d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fab_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('product_url', sa.Text(), nullable=True),
    sa.Column('file_format', sa.Text(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_url')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('alt', sa.Text(), nullable=True),
    sa.Column('preview', sa.Boolean(), nullable=True),
    sa.Column('fab_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fab_item_id'], ['fab_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_dimensions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('fab_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fab_item_id'], ['fab_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_dimensions')
    op.drop_table('images')
    op.drop_table('fab_items')
    # ### end Alembic commands ###
